### ISSUE TITLE
Tracking issue for githubteacher's workflow

### ISSUE THREAD

**Issue by CodeCrafter1** [githubteacher/github-august#146]
# Tracking issue
- [] create a branch
- [] add commits on my own branch
- [] open a PR pull request
- [] collaborate and have a conversation
- [] make some more commits
- [] merge branch into master
