### ISSUE TITLE
Tracking issue for githubteacher's workflow 

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/github-august#28]
# Tracking Issue
- [x] create a branch
- [x] add commits on my own branch
- [x] open a pull request
- [x] collaborate and have a conversation
- [x] make some more commits
- [x] merge branch into master

🍕 @beardofedu What do you think of these changes?
