### ISSUE TITLE
Tracking issue for shadow247's workflow

### ISSUE THREAD

**Issue by shadow247** [githubteacher/github-august#31]
# Tracking Issue
- [x] create a branch
- [x] add commits on my own branch
- [x] open a pull request
- [x] collaborate and have a conversation
- [x] make some more commits
- [ ] merge branch into master
