### ISSUE TITLE
Tracking issue for rwim2 workflow

### ISSUE THREAD

**Issue by rwim2** [githubteacher/github-august#32]
# Tracking Issue
- [x] create a branch
- [x] add commits on my own branch
- [x] open a Pull Request
- [x] collaborate and have a conversation
- [x] make some more commits
- [x] merge branch into master
