### ISSUE TITLE
Tracking issue for NatashaE's workflow

### ISSUE THREAD

**Issue by NatashaE** [githubteacher/github-august#34]
## Tracking Issue 🌊
- [x] create a branch
- [x] add commits on my own branch
- [x] open a PR (pull request)
- [x] collaborate and have a conversation
- [x] make some more commits
- [x] merge branch into master
