### ISSUE TITLE
Tracking issue for workflow - spydertad

### ISSUE THREAD

**Issue by spydertad** [githubteacher/github-august#35]
# Tracking Issue
- [ ] create a branch
- [ ] add commits feature branch
- [ ] open a pull request
- [ ] collaborate / review
- [ ] make commits
- [ ] merge branch into master
