### ISSUE TITLE
Tracking issue for jokan1 workflow

### ISSUE THREAD

**Issue by jokan1** [githubteacher/github-august#36]
# Tracker Issue
- [x] create a branch
- [x] add commits on my own branch
- [x] open a Pull Request
- [x] collaborate and have a conversation
- [ ] make some more commits
- [ ] merge branch into master

@beardofedu  - what do you think of these changes
