### ISSUE TITLE
Tracking issue for arachmiel's workflow

### ISSUE THREAD

**Issue by arachmiel** [githubteacher/github-august#37]
# Tracking Issue
- [x] create a branch
- [x] add commits on my own branch
- [x] open a pull request
- [x] collaborate and have a conversation
- [x] make some more commits
- [ ] merge branch into master

:coffee: @beardofedu
