### ISSUE TITLE
Tracking

### ISSUE THREAD

**Issue by ArthurZC23** [githubteacher/github-august#38]
# Tracking Issue
- [x] create a branch
- [x] add commits on my own branch
- [x] open a pull request
- [x] collaborate and have a conversation
- [x] make some more commits
- [x] merge branch into master
