### ISSUE TITLE
Tracking issue for Deneli workflow

### ISSUE THREAD

**Issue by Deneli** [githubteacher/github-august#40]
# Tracking issue
- [ ] create a branch
- [ ] add commits on my own branch
- [ ] open a PR
- [ ] collaborate and have a conversation
- [ ] make some more commits
- [ ] merge branch into
