### ISSUE TITLE
Tracking issue for Albert_Shamsiyan

### ISSUE THREAD

**Issue by AlbertShamsiyan** [githubteacher/github-august#41]
# Tracking issue
- [x] create branch 
- [ ] add commits on my own branch 
- [ ] open a PR
- [ ] make some more commits
- [ ] merge branch into master
