### ISSUE TITLE
Tracking issue for kmmonk's workflow

### ISSUE THREAD

**Issue by kmmonk** [githubteacher/github-august#43]
# Tracking Issue
- [x] create a branch
- [x] add commits on my own branch
- [x] open a PR (pull request)
- [x] collaborate and have a conversation
- [x] make some more commits
- [x] merge branch into master

🎉 @githubteacher how does this look? 🎉
