### ISSUE TITLE
Tracking issue for yangus1265's workflow

### ISSUE THREAD

**Issue by yangus1265** [githubteacher/github-august#48]
# Tracking issue
- [x] create a branch
- [x]  add commits on my own branch
- [x]  open a PR
- [x]  collaborate and have a conversation
- [ ]  make some more commits
- [ ]  merge branch into master
