### ISSUE TITLE
Tracking Issue for wielder02's workflow

### ISSUE THREAD

**Issue by wielder02** [githubteacher/github-august#50]
# Tracking Issue
- [ ] Create a brach
- [ ] add commits on my own branch
- [ ]  open RR
- [ ] collaborate and have a conversation
- [ ] make some more commits
- [ ] merge branch into master

@githubteacher What do you think?
