### ISSUE TITLE
[Critical] Tracking issue for DragonChr1s' workflow

### ISSUE THREAD

**Issue by DragonChr1s** [githubteacher/github-august#54]
# Snazzy
- [x] create a branch
- [x] add commits on my own branch
- [x] open a pull request (PR)
- [x] collaborate and have a conversation
- [x] make some more commits
- [ ] merge branch into master
