### ISSUE TITLE
Workflow tracker

### ISSUE THREAD

**Issue by ewanstronge** [githubteacher/github-august#56]
# Track Issue
- [x] create a branch
- [x] add commits on my own branch
- [ ] open a PR
- [ ] collaborate and have a conversation
- [ ] make some more commits
- [ ] merge branch into master

:gb: @beardofedu
