### ISSUE TITLE
Tracking issue for fjm's workflow

### ISSUE THREAD

**Issue by fjmurray** [githubteacher/github-august#60]
# Tracking Issue
- [x] create a branch
- [x] add commits on my own branch
- [x] open a PR (Pull Request)
- [x] collaborate and have a conversation
- [x] make some more commits
- [x] merge branch to master

**Comment by fjmurray** [comment]
Which gitter room are we supposed to be in?
