### ISSUE TITLE
Tracking issue for cwilson2

### ISSUE THREAD

**Issue by cwilson2** [githubteacher/github-august#63]
Tracking Issue
- [x] create a branch
- [x] add commits on my own branch
- [ ] open a PR
- [ ] collaborate and have a conversation
- [ ] make some more commits
- [ ] merge branch into master
