### ISSUE TITLE
Tracking issue cslagron

### ISSUE THREAD

**Issue by cslagron** [githubteacher/github-august#70]
# Tracking Issue
- [x]  create a branch
- [x]  add commits on my own branch
- [x]  open a PR
- [ ]  collaborate and have a conversation
- [ ]  make some more commits
- [ ]  merge branch into master
